---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that:
      - jenkins_agent_controller_public_key is defined

- name: Ensure jenkins group exists
  ansible.builtin.group:
    name: "{{ jenkins_agent_user }}"

- name: Ensure jenkins user exists
  ansible.builtin.user:
    name: "{{ jenkins_agent_user }}"
    home: "{{ jenkins_agent_home }}"
    shell: /bin/bash
    group: "{{ jenkins_agent_user }}"

- name: Ensure jenkins tools dir exists
  ansible.builtin.file:
    path: "{{ jenkins_agent_home }}/tools"
    state: directory
    mode: "0755"
    owner: "{{ jenkins_agent_user }}"
    group: "{{ jenkins_agent_user }}"

- name: Ensure .ssh dir exists
  ansible.builtin.file:
    path: "{{ jenkins_agent_home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ jenkins_agent_user }}"
    group: "{{ jenkins_agent_user }}"

- name: Add controller public key to authorized key
  ansible.posix.authorized_key:
    user: "{{ jenkins_agent_user }}"
    key: "{{ jenkins_agent_controller_public_key }}"

- name: Add remoting jar when required
  ansible.builtin.get_url:
    url: "{{ jenkins_agent_controller_endpoint }}/jnlpJars/remoting.jar"
    dest: "{{ jenkins_agent_home }}/remoting.jar"
    mode: "0755"
    owner: "{{ jenkins_agent_user }}"
    group: "{{ jenkins_agent_user }}"
  when: jenkins_agent_include_remoting
