---
- name: Add Adoptium key & repository
  ansible.builtin.deb822_repository:
    name: adoptium
    types:
      - deb
    uris: https://packages.adoptium.net/artifactory/deb
    signed_by: https://packages.adoptium.net/artifactory/api/gpg/key/public
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    enabled: true

- name: "Install JDK {{ java_version }}"
  ansible.builtin.apt:
    pkg: "temurin-{{ java_version }}-jdk"
    update_cache: true
