---
- name: Remove Adoptium key & repository
  ansible.builtin.deb822_repository:
    name: adoptium
    types:
      - deb
    uris: https://packages.adoptium.net/artifactory/deb
    signed_by: https://packages.adoptium.net/artifactory/api/gpg/key/public
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    state: absent

- name: Remove Adoptium GPG apt key
  ansible.builtin.apt_key:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public
    id: 3B04D753C9050D9A5D343F39843C48A565F8F04B
    state: absent
