---
- name: Install packages
  ansible.builtin.package:
    name:
      - file
      - libcap2-bin
      - openssl

- name: Create vault group
  ansible.builtin.group:
    name: "{{ vault_group }}"
    system: true

- name: Create vault user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    create_home: false
    system: true
    shell: "{{ vault_user_shell }}"
    group: "{{ vault_group }}"

- name: Create Vault download directory
  ansible.builtin.file:
    path: "{{ vault_download_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: Download Vault binary
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "{{ vault_download_path }}"
    creates: "{{ vault_download_path }}/vault"
    owner: root
    group: root
    mode: "0644"
    remote_src: true

- name: Create Vault config directory
  ansible.builtin.file:
    name: /etc/vault.d
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: Copy Vault binary
  ansible.builtin.copy:
    src: "{{ vault_download_path }}/vault"
    dest: /usr/bin/vault
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  notify:
    - Restart vault

- name: Set cap_ipc_lock=ep on /usr/bin/vault
  community.general.capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock+ep
  changed_when: false

- name: Copy Vault service file
  ansible.builtin.template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Daemon reload

- name: Copy vault configuration
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart vault

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
